app_name: demo
deploy_dir: /home/deploy/
maintainer_email: demo@gmail.com
app_domain: demo.com
deploy_user: deploy

# Nginx
nginx_https_enabled: true

# Server Locale
locale: en_US.UTF-8

# Swap
# Uncommend here and in /roles/common/tasks/main.yml
swap_file_path: /swapfile
swap_file_size_kb: 1024

# Rails
puma_workers: 4
puma_threads: 4,16

# Elasticsearch
elasticsearch_version: 6.6.1
