- name: 'Install Redis'
  become: true
  apt:
    name: 'redis-server'
    state: latest
    update_cache: true

- name: 'Ensure Redis Server is running'
  become: true
  service:
    name: redis-server
    state: started
    enabled: yes
