---
# Set up user accounts
- hosts: all
  remote_user: root
  become: yes
  roles:
    - common
    - user_creation

# Install NodeJS
- hosts: all
  remote_user: deploy
  become: true
  roles:
    - geerlingguy.nodejs
  vars:
    nodejs_version: "9.x"

# Set up all server installations
- hosts: all
  remote_user: deploy
  become: yes
  roles:
    - yarn
    - nginx
    # - certbot
    - ruby
    - postgres
    - rails
    - monit
    # - redis

#   hosts: all
#   roles:
#     - role: elastic.elasticsearch
#       es_instance_name: "node1"

# Now that everything is installed, set up logrotates
# - hosts: all
#   remote_user: root
#   become: true
#   roles:
#     - nickhammond.logrotate
#   vars:
#     logrotate_scripts:
#       - name: rails-logs
#         path: "{{ deploy_dir }}{{ app_name }}/shared/log/production.log"
#         options:
#           - daily
#           - size 25M
#           - rotate 7
#           - missingok
#           - compress
#           - delaycompress
#           - copytruncate
#       - name: sidekiq-logs
#         path: "{{ deploy_dir }}{{ app_name }}/shared/log/sidekiq.log"
#         options:
#           - daily
#           - size 25M
#           - rotate 7
#           - missingok
#           - compress
#           - delaycompress
#           - copytruncate
#       - name: postgres-backups
#         path: "/var/backups/postgres/{{ app_name }}_production.pgdump.gz"
#         options:
#           - daily
#           - size 25M
#           - rotate 7
#           - missingok
#           - compress
#           - delaycompress
#           - copytruncate
