- name: install node
  apt: pkg={{item}} state=present
  with_items:
  - nodejs
  - nodejs-legacy
  - npm

- name: install npm packages
  npm: name={{item}} global=yes
  with_items:
  - ember-cli
  - bower
  - phantomjs

- name: fetch from git
  git: repo={{calendarbin_repo}}
       force=yes
       depth=20
       dest={{calendarbin_path}}
       accept_hostkey=yes
  notify:
  - restart unicorn
  - restart sidekiq

- name: set file permissions
  file: path={{calendarbin_path}}
        state=directory
        recurse=yes
        owner=calendarbin
        group=www-data

- name: bundle install
  command: /bin/su calendarbin --login -c "cd {{calendarbin_path}} && bundle install --deployment --without test"

- name: npm and bower install
  command: /bin/su calendarbin --login -c "cd {{calendarbin_path}}/frontend && npm install && bower install"

- name: precompile assets
  command: /bin/su calendarbin --login -c "cd {{calendarbin_path}} && bundle exec rake assets:precompile EMBERCLI_COMPILE=1"

- name: migrate database
  command: /bin/su calendarbin --login -c "cd {{calendarbin_path}} && bundle exec rake db:migrate"

- name: copy unicorn monit conf
  template: src=unicorn.monit dest=/etc/monit/conf.d/unicorn.monit
  when: "'app' in group_names"
  notify:
  - reload monit
  - start unicorn

- name: copy sidekiq monit conf
  template: src=sidekiq.monit dest=/etc/monit/conf.d/sidekiq.monit
  when: "'sidekiq' in group_names"
  notify:
  - reload monit
  - start sidekiq
