- name: Create the deploy user
  user:
    name: "{{ deploy_user }}"
    comment:  User for Rails application deployment
    append: true
    shell: /bin/bash
    groups:
      - sudo

- name: Add developer deploy SSH keys
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ item }}"
  with_items:
    - https://github.com/murny.keys

- name: Remove sudo group rights
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    state: absent

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ deploy_user }} ALL"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart sshd
