- name: create calendarbin_production database
  postgresql_db: db=calendarbin
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'

- name: create calendarbin database user
  postgresql_user: db=calendarbin
                   user=calendarbin
                   password={{postgres_db_password}}
                   priv=ALL
